CREATE TABLE IF NOT EXISTS photos (
    id SERIAL PRIMARY KEY,
    photo_m VARCHAR(255) NOT NULL,
    business_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE
);